spring.application.name=Weather_app
weather.api.key=da1cb2db260445f5b44155009253010
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json
server.port=8082